# Generated by Django 5.2.4 on 2025-07-28 20:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
        ('users', '0003_facebookpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='facebook_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.facebookpage'),
        ),
    ]
